### ISSUE TITLE
Ajax 기능은 언제쯤 추가될까요?

### ISSUE THREAD

**Issue by qnibus** [nhnent/tui.component.tree#17]
안녕하세요!
NHN고도 안종태 qnibus@godo.co.kr라고 합니다.

저희가 해당 콤포넌트를 사용하고 있는데요!
Ajax 기능이 필요한데 혹 추가하실 예정이 있으신지요?
있으시다면 언제쯤일지 궁금해서 질문드립니다.

게시판의 성격과 맞지 않으면 글 보시고 지우셔도 되오며,
이메일로라도 답변 좀 해주셨으면 정말 감사하겠습니다.
수고하세요!

**Comment by seonim-ryu** [comment]
안녕하세요 :) NHN 엔터테인먼트 FE개발랩입니다.
문의 주신 내용에 대해서는 메일로 회신 드리겠습니다.
감사합니다.
