### ISSUE TITLE
template에 string이 아닌 값을 넣을 수 있나요?

### ISSUE THREAD

**Issue by seulgi0711** [nhnent/tui.component.tree#19]
안녕하세요 협업시스템개발팀 성슬기입니다.
이번에 메신저에서 tree 컴포넌트를 사용하려고 하는데요.
문서를 살펴보니 template 옵션에 internalNode와 leafNode에 string만 가능한 것 같은데요 혹시 element나 jquery 객체를 쓸 수는 없나요??

그리고 한가지 더...
템플릿에서 {{text}} 이렇게 사용하도록 되어있는데요.
현재 메신저가 angular를 사용중입니다. angular에서 사용중인 interpolation 문자가 {{스코프변수}} 이런식으로 되어있습니다. 혹시 첫 번째 문의 드린 내용이 가능하다면 angular와 사용했을때 충돌이 생길것 같은데요. interpolation 문자를 다른 문자로 바꿀 수 있는 옵션이 있을까요??

**Comment by seonim-ryu** [comment]
안녕하세요. FE 개발랩입니다 :)

현재 `template` 옵션은 `string` 값만 받을 수 있으나,
`renderTemplate` 옵션을 사용하면 문의주신 내용에 대한 처리가 가능할 것으로 보입니다.

```js
var tree = new tui.component.Tree(data, {
    rootElement: 'treeRoot', // or document.getElementById('treeRoot')
    nodeDefaultState: 'opened',

    // ========= Option: Override template renderer ===========
    template: { // template for Mustache engine
        internalNode:
            '<button type="button" class="{{toggleBtnClass}}">{{stateLabel}}</button>' +
                '<span class="{{textClass}}">{{text}}</span>' +
                '<ul class="{{subtreeClass}}">{{children}}</ul>',
        leafNode:
            '<span class="{{textClass}}">{{text}}</span>'
    },
    renderTemplate: function(tmpl, props) {
        // Mustache template engine
        return Mustache.render(tmpl, props);
    }
});
```
추가로 interpolation 문자를 다른 문자로 치환하는 옵션은 제공하고 있지 않습니다.

`renderTemplate` 옵션 사용을 검토해 보시고 사용 중에 궁금하신 점 있으신 경우 문의주시면 도움드리겠습니다.

감사합니다 :)
